// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	strconv "strconv"
)

type AccountType uint16

// AccountType_TypeID is the unique identifier for the type AccountType.
const AccountType_TypeID = 0xa309701d252a3266

// Values of AccountType.
const (
	AccountType_unknown            AccountType = 0
	AccountType_claudeSubscription AccountType = 1
	AccountType_claudePayAsYouGo   AccountType = 2
	AccountType_codexSubscription  AccountType = 3
	AccountType_geminiSubscription AccountType = 4
	AccountType_geminiApiKey       AccountType = 5
	AccountType_awsBedrock         AccountType = 6
)

// String returns the enum's constant name.
func (c AccountType) String() string {
	switch c {
	case AccountType_unknown:
		return "unknown"
	case AccountType_claudeSubscription:
		return "claudeSubscription"
	case AccountType_claudePayAsYouGo:
		return "claudePayAsYouGo"
	case AccountType_codexSubscription:
		return "codexSubscription"
	case AccountType_geminiSubscription:
		return "geminiSubscription"
	case AccountType_geminiApiKey:
		return "geminiApiKey"
	case AccountType_awsBedrock:
		return "awsBedrock"

	default:
		return ""
	}
}

// AccountTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func AccountTypeFromString(c string) AccountType {
	switch c {
	case "unknown":
		return AccountType_unknown
	case "claudeSubscription":
		return AccountType_claudeSubscription
	case "claudePayAsYouGo":
		return AccountType_claudePayAsYouGo
	case "codexSubscription":
		return AccountType_codexSubscription
	case "geminiSubscription":
		return AccountType_geminiSubscription
	case "geminiApiKey":
		return AccountType_geminiApiKey
	case "awsBedrock":
		return AccountType_awsBedrock

	default:
		return 0
	}
}

type AccountType_List = capnp.EnumList[AccountType]

func NewAccountType_List(s *capnp.Segment, sz int32) (AccountType_List, error) {
	return capnp.NewEnumList[AccountType](s, sz)
}

type ClaudeTokenCredentials capnp.Struct

// ClaudeTokenCredentials_TypeID is the unique identifier for the type ClaudeTokenCredentials.
const ClaudeTokenCredentials_TypeID = 0xf49df8ad98c6b0a0

func NewClaudeTokenCredentials(s *capnp.Segment) (ClaudeTokenCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeTokenCredentials(st), err
}

func NewRootClaudeTokenCredentials(s *capnp.Segment) (ClaudeTokenCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeTokenCredentials(st), err
}

func ReadRootClaudeTokenCredentials(msg *capnp.Message) (ClaudeTokenCredentials, error) {
	root, err := msg.Root()
	return ClaudeTokenCredentials(root.Struct()), err
}

func (s ClaudeTokenCredentials) String() string {
	str, _ := text.Marshal(0xf49df8ad98c6b0a0, capnp.Struct(s))
	return str
}

func (s ClaudeTokenCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeTokenCredentials) DecodeFromPtr(p capnp.Ptr) ClaudeTokenCredentials {
	return ClaudeTokenCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeTokenCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeTokenCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeTokenCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeTokenCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeTokenCredentials) AccessToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeTokenCredentials) HasAccessToken() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeTokenCredentials) AccessTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeTokenCredentials) SetAccessToken(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeTokenCredentials) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeTokenCredentials) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeTokenCredentials) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeTokenCredentials) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ClaudeTokenCredentials_List is a list of ClaudeTokenCredentials.
type ClaudeTokenCredentials_List = capnp.StructList[ClaudeTokenCredentials]

// NewClaudeTokenCredentials creates a new list of ClaudeTokenCredentials.
func NewClaudeTokenCredentials_List(s *capnp.Segment, sz int32) (ClaudeTokenCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ClaudeTokenCredentials](l), err
}

// ClaudeTokenCredentials_Future is a wrapper for a ClaudeTokenCredentials promised by a client call.
type ClaudeTokenCredentials_Future struct{ *capnp.Future }

func (f ClaudeTokenCredentials_Future) Struct() (ClaudeTokenCredentials, error) {
	p, err := f.Future.Ptr()
	return ClaudeTokenCredentials(p.Struct()), err
}

type ClaudeApiKeyCredentials capnp.Struct

// ClaudeApiKeyCredentials_TypeID is the unique identifier for the type ClaudeApiKeyCredentials.
const ClaudeApiKeyCredentials_TypeID = 0x8ef23c1999b62e1f

func NewClaudeApiKeyCredentials(s *capnp.Segment) (ClaudeApiKeyCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeApiKeyCredentials(st), err
}

func NewRootClaudeApiKeyCredentials(s *capnp.Segment) (ClaudeApiKeyCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ClaudeApiKeyCredentials(st), err
}

func ReadRootClaudeApiKeyCredentials(msg *capnp.Message) (ClaudeApiKeyCredentials, error) {
	root, err := msg.Root()
	return ClaudeApiKeyCredentials(root.Struct()), err
}

func (s ClaudeApiKeyCredentials) String() string {
	str, _ := text.Marshal(0x8ef23c1999b62e1f, capnp.Struct(s))
	return str
}

func (s ClaudeApiKeyCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClaudeApiKeyCredentials) DecodeFromPtr(p capnp.Ptr) ClaudeApiKeyCredentials {
	return ClaudeApiKeyCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClaudeApiKeyCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClaudeApiKeyCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClaudeApiKeyCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClaudeApiKeyCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClaudeApiKeyCredentials) ApiKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClaudeApiKeyCredentials) HasApiKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClaudeApiKeyCredentials) ApiKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClaudeApiKeyCredentials) SetApiKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ClaudeApiKeyCredentials) BaseUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ClaudeApiKeyCredentials) HasBaseUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ClaudeApiKeyCredentials) BaseUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ClaudeApiKeyCredentials) SetBaseUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ClaudeApiKeyCredentials_List is a list of ClaudeApiKeyCredentials.
type ClaudeApiKeyCredentials_List = capnp.StructList[ClaudeApiKeyCredentials]

// NewClaudeApiKeyCredentials creates a new list of ClaudeApiKeyCredentials.
func NewClaudeApiKeyCredentials_List(s *capnp.Segment, sz int32) (ClaudeApiKeyCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ClaudeApiKeyCredentials](l), err
}

// ClaudeApiKeyCredentials_Future is a wrapper for a ClaudeApiKeyCredentials promised by a client call.
type ClaudeApiKeyCredentials_Future struct{ *capnp.Future }

func (f ClaudeApiKeyCredentials_Future) Struct() (ClaudeApiKeyCredentials, error) {
	p, err := f.Future.Ptr()
	return ClaudeApiKeyCredentials(p.Struct()), err
}

type AccountCredentials capnp.Struct
type AccountCredentials_Which uint16

const (
	AccountCredentials_Which_none              AccountCredentials_Which = 0
	AccountCredentials_Which_claudeSubCreds    AccountCredentials_Which = 1
	AccountCredentials_Which_claudeApiKeyCreds AccountCredentials_Which = 2
)

func (w AccountCredentials_Which) String() string {
	const s = "noneclaudeSubCredsclaudeApiKeyCreds"
	switch w {
	case AccountCredentials_Which_none:
		return s[0:4]
	case AccountCredentials_Which_claudeSubCreds:
		return s[4:18]
	case AccountCredentials_Which_claudeApiKeyCreds:
		return s[18:35]

	}
	return "AccountCredentials_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// AccountCredentials_TypeID is the unique identifier for the type AccountCredentials.
const AccountCredentials_TypeID = 0xc80017a258c68a97

func NewAccountCredentials(s *capnp.Segment) (AccountCredentials, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountCredentials(st), err
}

func NewRootAccountCredentials(s *capnp.Segment) (AccountCredentials, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountCredentials(st), err
}

func ReadRootAccountCredentials(msg *capnp.Message) (AccountCredentials, error) {
	root, err := msg.Root()
	return AccountCredentials(root.Struct()), err
}

func (s AccountCredentials) String() string {
	str, _ := text.Marshal(0xc80017a258c68a97, capnp.Struct(s))
	return str
}

func (s AccountCredentials) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountCredentials) DecodeFromPtr(p capnp.Ptr) AccountCredentials {
	return AccountCredentials(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountCredentials) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s AccountCredentials) Which() AccountCredentials_Which {
	return AccountCredentials_Which(capnp.Struct(s).Uint16(0))
}
func (s AccountCredentials) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountCredentials) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountCredentials) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountCredentials) SetNone() {
	capnp.Struct(s).SetUint16(0, 0)

}

func (s AccountCredentials) ClaudeSubCreds() (ClaudeTokenCredentials, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != claudeSubCreds")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ClaudeTokenCredentials(p.Struct()), err
}

func (s AccountCredentials) HasClaudeSubCreds() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountCredentials) SetClaudeSubCreds(v ClaudeTokenCredentials) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClaudeSubCreds sets the claudeSubCreds field to a newly
// allocated ClaudeTokenCredentials struct, preferring placement in s's segment.
func (s AccountCredentials) NewClaudeSubCreds() (ClaudeTokenCredentials, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewClaudeTokenCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeTokenCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AccountCredentials) ClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != claudeApiKeyCreds")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ClaudeApiKeyCredentials(p.Struct()), err
}

func (s AccountCredentials) HasClaudeApiKeyCreds() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountCredentials) SetClaudeApiKeyCreds(v ClaudeApiKeyCredentials) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewClaudeApiKeyCreds sets the claudeApiKeyCreds field to a newly
// allocated ClaudeApiKeyCredentials struct, preferring placement in s's segment.
func (s AccountCredentials) NewClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewClaudeApiKeyCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeApiKeyCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountCredentials_List is a list of AccountCredentials.
type AccountCredentials_List = capnp.StructList[AccountCredentials]

// NewAccountCredentials creates a new list of AccountCredentials.
func NewAccountCredentials_List(s *capnp.Segment, sz int32) (AccountCredentials_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountCredentials](l), err
}

// AccountCredentials_Future is a wrapper for a AccountCredentials promised by a client call.
type AccountCredentials_Future struct{ *capnp.Future }

func (f AccountCredentials_Future) Struct() (AccountCredentials, error) {
	p, err := f.Future.Ptr()
	return AccountCredentials(p.Struct()), err
}
func (p AccountCredentials_Future) ClaudeSubCreds() ClaudeTokenCredentials_Future {
	return ClaudeTokenCredentials_Future{Future: p.Future.Field(0, nil)}
}
func (p AccountCredentials_Future) ClaudeApiKeyCreds() ClaudeApiKeyCredentials_Future {
	return ClaudeApiKeyCredentials_Future{Future: p.Future.Field(0, nil)}
}

type AccountInfo capnp.Struct

// AccountInfo_TypeID is the unique identifier for the type AccountInfo.
const AccountInfo_TypeID = 0xde341fe554ef796d

func NewAccountInfo(s *capnp.Segment) (AccountInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountInfo(st), err
}

func NewRootAccountInfo(s *capnp.Segment) (AccountInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountInfo(st), err
}

func ReadRootAccountInfo(msg *capnp.Message) (AccountInfo, error) {
	root, err := msg.Root()
	return AccountInfo(root.Struct()), err
}

func (s AccountInfo) String() string {
	str, _ := text.Marshal(0xde341fe554ef796d, capnp.Struct(s))
	return str
}

func (s AccountInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountInfo) DecodeFromPtr(p capnp.Ptr) AccountInfo {
	return AccountInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountInfo) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountInfo) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountInfo) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountInfo) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountInfo) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountInfo) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountInfo) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountInfo) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountInfo) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountInfo) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountInfo) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountInfo) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountInfo) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountInfo) SetVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountInfo) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AccountInfo) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s AccountInfo) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountInfo) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountInfo) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountInfo) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountInfo) Credentials() (AccountCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AccountCredentials(p.Struct()), err
}

func (s AccountInfo) HasCredentials() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountInfo) SetCredentials(v AccountCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewCredentials sets the credentials field to a newly
// allocated AccountCredentials struct, preferring placement in s's segment.
func (s AccountInfo) NewCredentials() (AccountCredentials, error) {
	ss, err := NewAccountCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return AccountCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountInfo_List is a list of AccountInfo.
type AccountInfo_List = capnp.StructList[AccountInfo]

// NewAccountInfo creates a new list of AccountInfo.
func NewAccountInfo_List(s *capnp.Segment, sz int32) (AccountInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5}, sz)
	return capnp.StructList[AccountInfo](l), err
}

// AccountInfo_Future is a wrapper for a AccountInfo promised by a client call.
type AccountInfo_Future struct{ *capnp.Future }

func (f AccountInfo_Future) Struct() (AccountInfo, error) {
	p, err := f.Future.Ptr()
	return AccountInfo(p.Struct()), err
}
func (p AccountInfo_Future) Credentials() AccountCredentials_Future {
	return AccountCredentials_Future{Future: p.Future.Field(4, nil)}
}

type AccountService capnp.Client

// AccountService_TypeID is the unique identifier for the type AccountService.
const AccountService_TypeID = 0x8a9179019ae6c648

func (c AccountService) RegisterAccount(ctx context.Context, params func(AccountService_registerAccount_Params) error) (AccountService_registerAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      0,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "registerAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 5}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_registerAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_registerAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) UpdateAccount(ctx context.Context, params func(AccountService_updateAccount_Params) error) (AccountService_updateAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      1,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "updateAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 6}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_updateAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_updateAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) RemoveAccount(ctx context.Context, params func(AccountService_removeAccount_Params) error) (AccountService_removeAccount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      2,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "removeAccount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_removeAccount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_removeAccount_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) ListAccounts(ctx context.Context, params func(AccountService_listAccounts_Params) error) (AccountService_listAccounts_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      3,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "listAccounts",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AccountService_listAccounts_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AccountService_listAccounts_Results_Future{Future: ans.Future()}, release

}

func (c AccountService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c AccountService) String() string {
	return "AccountService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c AccountService) AddRef() AccountService {
	return AccountService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c AccountService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c AccountService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c AccountService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (AccountService) DecodeFromPtr(p capnp.Ptr) AccountService {
	return AccountService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c AccountService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c AccountService) IsSame(other AccountService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c AccountService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c AccountService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A AccountService_Server is a AccountService with a local implementation.
type AccountService_Server interface {
	RegisterAccount(context.Context, AccountService_registerAccount) error

	UpdateAccount(context.Context, AccountService_updateAccount) error

	RemoveAccount(context.Context, AccountService_removeAccount) error

	ListAccounts(context.Context, AccountService_listAccounts) error
}

// AccountService_NewServer creates a new Server from an implementation of AccountService_Server.
func AccountService_NewServer(s AccountService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(AccountService_Methods(nil, s), s, c)
}

// AccountService_ServerToClient creates a new Client from an implementation of AccountService_Server.
// The caller is responsible for calling Release on the returned Client.
func AccountService_ServerToClient(s AccountService_Server) AccountService {
	return AccountService(capnp.NewClient(AccountService_NewServer(s)))
}

// AccountService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func AccountService_Methods(methods []server.Method, s AccountService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      0,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "registerAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RegisterAccount(ctx, AccountService_registerAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      1,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "updateAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.UpdateAccount(ctx, AccountService_updateAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      2,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "removeAccount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RemoveAccount(ctx, AccountService_removeAccount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a9179019ae6c648,
			MethodID:      3,
			InterfaceName: "account.capnp:AccountService",
			MethodName:    "listAccounts",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListAccounts(ctx, AccountService_listAccounts{call})
		},
	})

	return methods
}

// AccountService_registerAccount holds the state for a server call to AccountService.registerAccount.
// See server.Call for documentation.
type AccountService_registerAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_registerAccount) Args() AccountService_registerAccount_Params {
	return AccountService_registerAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_registerAccount) AllocResults() (AccountService_registerAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(r), err
}

// AccountService_updateAccount holds the state for a server call to AccountService.updateAccount.
// See server.Call for documentation.
type AccountService_updateAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_updateAccount) Args() AccountService_updateAccount_Params {
	return AccountService_updateAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_updateAccount) AllocResults() (AccountService_updateAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(r), err
}

// AccountService_removeAccount holds the state for a server call to AccountService.removeAccount.
// See server.Call for documentation.
type AccountService_removeAccount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_removeAccount) Args() AccountService_removeAccount_Params {
	return AccountService_removeAccount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_removeAccount) AllocResults() (AccountService_removeAccount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(r), err
}

// AccountService_listAccounts holds the state for a server call to AccountService.listAccounts.
// See server.Call for documentation.
type AccountService_listAccounts struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AccountService_listAccounts) Args() AccountService_listAccounts_Params {
	return AccountService_listAccounts_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AccountService_listAccounts) AllocResults() (AccountService_listAccounts_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(r), err
}

// AccountService_List is a list of AccountService.
type AccountService_List = capnp.CapList[AccountService]

// NewAccountService_List creates a new list of AccountService.
func NewAccountService_List(s *capnp.Segment, sz int32) (AccountService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[AccountService](l), err
}

type AccountService_registerAccount_Params capnp.Struct

// AccountService_registerAccount_Params_TypeID is the unique identifier for the type AccountService_registerAccount_Params.
const AccountService_registerAccount_Params_TypeID = 0xa77c56c45e37a0a1

func NewAccountService_registerAccount_Params(s *capnp.Segment) (AccountService_registerAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountService_registerAccount_Params(st), err
}

func NewRootAccountService_registerAccount_Params(s *capnp.Segment) (AccountService_registerAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5})
	return AccountService_registerAccount_Params(st), err
}

func ReadRootAccountService_registerAccount_Params(msg *capnp.Message) (AccountService_registerAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_registerAccount_Params(root.Struct()), err
}

func (s AccountService_registerAccount_Params) String() string {
	str, _ := text.Marshal(0xa77c56c45e37a0a1, capnp.Struct(s))
	return str
}

func (s AccountService_registerAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_registerAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_registerAccount_Params {
	return AccountService_registerAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_registerAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_registerAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_registerAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_registerAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_registerAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_registerAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountService_registerAccount_Params) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountService_registerAccount_Params) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountService_registerAccount_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountService_registerAccount_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountService_registerAccount_Params) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountService_registerAccount_Params) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountService_registerAccount_Params) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountService_registerAccount_Params) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountService_registerAccount_Params) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Params) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountService_registerAccount_Params) ExpiresIn() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AccountService_registerAccount_Params) SetExpiresIn(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s AccountService_registerAccount_Params) Credentials() (AccountCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AccountCredentials(p.Struct()), err
}

func (s AccountService_registerAccount_Params) HasCredentials() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountService_registerAccount_Params) SetCredentials(v AccountCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewCredentials sets the credentials field to a newly
// allocated AccountCredentials struct, preferring placement in s's segment.
func (s AccountService_registerAccount_Params) NewCredentials() (AccountCredentials, error) {
	ss, err := NewAccountCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return AccountCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountService_registerAccount_Params_List is a list of AccountService_registerAccount_Params.
type AccountService_registerAccount_Params_List = capnp.StructList[AccountService_registerAccount_Params]

// NewAccountService_registerAccount_Params creates a new list of AccountService_registerAccount_Params.
func NewAccountService_registerAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_registerAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 5}, sz)
	return capnp.StructList[AccountService_registerAccount_Params](l), err
}

// AccountService_registerAccount_Params_Future is a wrapper for a AccountService_registerAccount_Params promised by a client call.
type AccountService_registerAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_registerAccount_Params_Future) Struct() (AccountService_registerAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_registerAccount_Params(p.Struct()), err
}
func (p AccountService_registerAccount_Params_Future) Credentials() AccountCredentials_Future {
	return AccountCredentials_Future{Future: p.Future.Field(4, nil)}
}

type AccountService_registerAccount_Results capnp.Struct

// AccountService_registerAccount_Results_TypeID is the unique identifier for the type AccountService_registerAccount_Results.
const AccountService_registerAccount_Results_TypeID = 0xcd61f2c9baeb2c70

func NewAccountService_registerAccount_Results(s *capnp.Segment) (AccountService_registerAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(st), err
}

func NewRootAccountService_registerAccount_Results(s *capnp.Segment) (AccountService_registerAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_registerAccount_Results(st), err
}

func ReadRootAccountService_registerAccount_Results(msg *capnp.Message) (AccountService_registerAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_registerAccount_Results(root.Struct()), err
}

func (s AccountService_registerAccount_Results) String() string {
	str, _ := text.Marshal(0xcd61f2c9baeb2c70, capnp.Struct(s))
	return str
}

func (s AccountService_registerAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_registerAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_registerAccount_Results {
	return AccountService_registerAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_registerAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_registerAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_registerAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_registerAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_registerAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_registerAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_registerAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_registerAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_registerAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_registerAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_registerAccount_Results_List is a list of AccountService_registerAccount_Results.
type AccountService_registerAccount_Results_List = capnp.StructList[AccountService_registerAccount_Results]

// NewAccountService_registerAccount_Results creates a new list of AccountService_registerAccount_Results.
func NewAccountService_registerAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_registerAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_registerAccount_Results](l), err
}

// AccountService_registerAccount_Results_Future is a wrapper for a AccountService_registerAccount_Results promised by a client call.
type AccountService_registerAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_registerAccount_Results_Future) Struct() (AccountService_registerAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_registerAccount_Results(p.Struct()), err
}

type AccountService_updateAccount_Params capnp.Struct

// AccountService_updateAccount_Params_TypeID is the unique identifier for the type AccountService_updateAccount_Params.
const AccountService_updateAccount_Params_TypeID = 0x891fa8b6066a4ed5

func NewAccountService_updateAccount_Params(s *capnp.Segment) (AccountService_updateAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return AccountService_updateAccount_Params(st), err
}

func NewRootAccountService_updateAccount_Params(s *capnp.Segment) (AccountService_updateAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return AccountService_updateAccount_Params(st), err
}

func ReadRootAccountService_updateAccount_Params(msg *capnp.Message) (AccountService_updateAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_updateAccount_Params(root.Struct()), err
}

func (s AccountService_updateAccount_Params) String() string {
	str, _ := text.Marshal(0x891fa8b6066a4ed5, capnp.Struct(s))
	return str
}

func (s AccountService_updateAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_updateAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_updateAccount_Params {
	return AccountService_updateAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_updateAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_updateAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_updateAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_updateAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_updateAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_updateAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AccountService_updateAccount_Params) AccountType() AccountType {
	return AccountType(capnp.Struct(s).Uint16(0))
}

func (s AccountService_updateAccount_Params) SetAccountType(v AccountType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AccountService_updateAccount_Params) ProxyUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasProxyUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccountService_updateAccount_Params) ProxyUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetProxyUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AccountService_updateAccount_Params) ConfigJson() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasConfigJson() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AccountService_updateAccount_Params) ConfigJsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetConfigJson(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AccountService_updateAccount_Params) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AccountService_updateAccount_Params) HasVersion() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AccountService_updateAccount_Params) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Params) SetVersion(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AccountService_updateAccount_Params) ClaudeSubCreds() (ClaudeTokenCredentials, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return ClaudeTokenCredentials(p.Struct()), err
}

func (s AccountService_updateAccount_Params) HasClaudeSubCreds() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AccountService_updateAccount_Params) SetClaudeSubCreds(v ClaudeTokenCredentials) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewClaudeSubCreds sets the claudeSubCreds field to a newly
// allocated ClaudeTokenCredentials struct, preferring placement in s's segment.
func (s AccountService_updateAccount_Params) NewClaudeSubCreds() (ClaudeTokenCredentials, error) {
	ss, err := NewClaudeTokenCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeTokenCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AccountService_updateAccount_Params) ClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return ClaudeApiKeyCredentials(p.Struct()), err
}

func (s AccountService_updateAccount_Params) HasClaudeApiKeyCreds() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s AccountService_updateAccount_Params) SetClaudeApiKeyCreds(v ClaudeApiKeyCredentials) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewClaudeApiKeyCreds sets the claudeApiKeyCreds field to a newly
// allocated ClaudeApiKeyCredentials struct, preferring placement in s's segment.
func (s AccountService_updateAccount_Params) NewClaudeApiKeyCreds() (ClaudeApiKeyCredentials, error) {
	ss, err := NewClaudeApiKeyCredentials(capnp.Struct(s).Segment())
	if err != nil {
		return ClaudeApiKeyCredentials{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

// AccountService_updateAccount_Params_List is a list of AccountService_updateAccount_Params.
type AccountService_updateAccount_Params_List = capnp.StructList[AccountService_updateAccount_Params]

// NewAccountService_updateAccount_Params creates a new list of AccountService_updateAccount_Params.
func NewAccountService_updateAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_updateAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6}, sz)
	return capnp.StructList[AccountService_updateAccount_Params](l), err
}

// AccountService_updateAccount_Params_Future is a wrapper for a AccountService_updateAccount_Params promised by a client call.
type AccountService_updateAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_updateAccount_Params_Future) Struct() (AccountService_updateAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_updateAccount_Params(p.Struct()), err
}
func (p AccountService_updateAccount_Params_Future) ClaudeSubCreds() ClaudeTokenCredentials_Future {
	return ClaudeTokenCredentials_Future{Future: p.Future.Field(4, nil)}
}
func (p AccountService_updateAccount_Params_Future) ClaudeApiKeyCreds() ClaudeApiKeyCredentials_Future {
	return ClaudeApiKeyCredentials_Future{Future: p.Future.Field(5, nil)}
}

type AccountService_updateAccount_Results capnp.Struct

// AccountService_updateAccount_Results_TypeID is the unique identifier for the type AccountService_updateAccount_Results.
const AccountService_updateAccount_Results_TypeID = 0xe83dabed9b090802

func NewAccountService_updateAccount_Results(s *capnp.Segment) (AccountService_updateAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(st), err
}

func NewRootAccountService_updateAccount_Results(s *capnp.Segment) (AccountService_updateAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_updateAccount_Results(st), err
}

func ReadRootAccountService_updateAccount_Results(msg *capnp.Message) (AccountService_updateAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_updateAccount_Results(root.Struct()), err
}

func (s AccountService_updateAccount_Results) String() string {
	str, _ := text.Marshal(0xe83dabed9b090802, capnp.Struct(s))
	return str
}

func (s AccountService_updateAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_updateAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_updateAccount_Results {
	return AccountService_updateAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_updateAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_updateAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_updateAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_updateAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_updateAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_updateAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_updateAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_updateAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_updateAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_updateAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_updateAccount_Results_List is a list of AccountService_updateAccount_Results.
type AccountService_updateAccount_Results_List = capnp.StructList[AccountService_updateAccount_Results]

// NewAccountService_updateAccount_Results creates a new list of AccountService_updateAccount_Results.
func NewAccountService_updateAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_updateAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_updateAccount_Results](l), err
}

// AccountService_updateAccount_Results_Future is a wrapper for a AccountService_updateAccount_Results promised by a client call.
type AccountService_updateAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_updateAccount_Results_Future) Struct() (AccountService_updateAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_updateAccount_Results(p.Struct()), err
}

type AccountService_removeAccount_Params capnp.Struct

// AccountService_removeAccount_Params_TypeID is the unique identifier for the type AccountService_removeAccount_Params.
const AccountService_removeAccount_Params_TypeID = 0xcfdc97e955c82412

func NewAccountService_removeAccount_Params(s *capnp.Segment) (AccountService_removeAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_removeAccount_Params(st), err
}

func NewRootAccountService_removeAccount_Params(s *capnp.Segment) (AccountService_removeAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_removeAccount_Params(st), err
}

func ReadRootAccountService_removeAccount_Params(msg *capnp.Message) (AccountService_removeAccount_Params, error) {
	root, err := msg.Root()
	return AccountService_removeAccount_Params(root.Struct()), err
}

func (s AccountService_removeAccount_Params) String() string {
	str, _ := text.Marshal(0xcfdc97e955c82412, capnp.Struct(s))
	return str
}

func (s AccountService_removeAccount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_removeAccount_Params) DecodeFromPtr(p capnp.Ptr) AccountService_removeAccount_Params {
	return AccountService_removeAccount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_removeAccount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_removeAccount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_removeAccount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_removeAccount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_removeAccount_Params) AccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_removeAccount_Params) HasAccountId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_removeAccount_Params) AccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_removeAccount_Params) SetAccountId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_removeAccount_Params_List is a list of AccountService_removeAccount_Params.
type AccountService_removeAccount_Params_List = capnp.StructList[AccountService_removeAccount_Params]

// NewAccountService_removeAccount_Params creates a new list of AccountService_removeAccount_Params.
func NewAccountService_removeAccount_Params_List(s *capnp.Segment, sz int32) (AccountService_removeAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_removeAccount_Params](l), err
}

// AccountService_removeAccount_Params_Future is a wrapper for a AccountService_removeAccount_Params promised by a client call.
type AccountService_removeAccount_Params_Future struct{ *capnp.Future }

func (f AccountService_removeAccount_Params_Future) Struct() (AccountService_removeAccount_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_removeAccount_Params(p.Struct()), err
}

type AccountService_removeAccount_Results capnp.Struct

// AccountService_removeAccount_Results_TypeID is the unique identifier for the type AccountService_removeAccount_Results.
const AccountService_removeAccount_Results_TypeID = 0xf69c1e2bdba142bf

func NewAccountService_removeAccount_Results(s *capnp.Segment) (AccountService_removeAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(st), err
}

func NewRootAccountService_removeAccount_Results(s *capnp.Segment) (AccountService_removeAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return AccountService_removeAccount_Results(st), err
}

func ReadRootAccountService_removeAccount_Results(msg *capnp.Message) (AccountService_removeAccount_Results, error) {
	root, err := msg.Root()
	return AccountService_removeAccount_Results(root.Struct()), err
}

func (s AccountService_removeAccount_Results) String() string {
	str, _ := text.Marshal(0xf69c1e2bdba142bf, capnp.Struct(s))
	return str
}

func (s AccountService_removeAccount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_removeAccount_Results) DecodeFromPtr(p capnp.Ptr) AccountService_removeAccount_Results {
	return AccountService_removeAccount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_removeAccount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_removeAccount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_removeAccount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_removeAccount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_removeAccount_Results) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s AccountService_removeAccount_Results) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s AccountService_removeAccount_Results) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AccountService_removeAccount_Results) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_removeAccount_Results) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AccountService_removeAccount_Results) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// AccountService_removeAccount_Results_List is a list of AccountService_removeAccount_Results.
type AccountService_removeAccount_Results_List = capnp.StructList[AccountService_removeAccount_Results]

// NewAccountService_removeAccount_Results creates a new list of AccountService_removeAccount_Results.
func NewAccountService_removeAccount_Results_List(s *capnp.Segment, sz int32) (AccountService_removeAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_removeAccount_Results](l), err
}

// AccountService_removeAccount_Results_Future is a wrapper for a AccountService_removeAccount_Results promised by a client call.
type AccountService_removeAccount_Results_Future struct{ *capnp.Future }

func (f AccountService_removeAccount_Results_Future) Struct() (AccountService_removeAccount_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_removeAccount_Results(p.Struct()), err
}

type AccountService_listAccounts_Params capnp.Struct

// AccountService_listAccounts_Params_TypeID is the unique identifier for the type AccountService_listAccounts_Params.
const AccountService_listAccounts_Params_TypeID = 0x92070f51247244e5

func NewAccountService_listAccounts_Params(s *capnp.Segment) (AccountService_listAccounts_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AccountService_listAccounts_Params(st), err
}

func NewRootAccountService_listAccounts_Params(s *capnp.Segment) (AccountService_listAccounts_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AccountService_listAccounts_Params(st), err
}

func ReadRootAccountService_listAccounts_Params(msg *capnp.Message) (AccountService_listAccounts_Params, error) {
	root, err := msg.Root()
	return AccountService_listAccounts_Params(root.Struct()), err
}

func (s AccountService_listAccounts_Params) String() string {
	str, _ := text.Marshal(0x92070f51247244e5, capnp.Struct(s))
	return str
}

func (s AccountService_listAccounts_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_listAccounts_Params) DecodeFromPtr(p capnp.Ptr) AccountService_listAccounts_Params {
	return AccountService_listAccounts_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_listAccounts_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_listAccounts_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_listAccounts_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_listAccounts_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// AccountService_listAccounts_Params_List is a list of AccountService_listAccounts_Params.
type AccountService_listAccounts_Params_List = capnp.StructList[AccountService_listAccounts_Params]

// NewAccountService_listAccounts_Params creates a new list of AccountService_listAccounts_Params.
func NewAccountService_listAccounts_Params_List(s *capnp.Segment, sz int32) (AccountService_listAccounts_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[AccountService_listAccounts_Params](l), err
}

// AccountService_listAccounts_Params_Future is a wrapper for a AccountService_listAccounts_Params promised by a client call.
type AccountService_listAccounts_Params_Future struct{ *capnp.Future }

func (f AccountService_listAccounts_Params_Future) Struct() (AccountService_listAccounts_Params, error) {
	p, err := f.Future.Ptr()
	return AccountService_listAccounts_Params(p.Struct()), err
}

type AccountService_listAccounts_Results capnp.Struct

// AccountService_listAccounts_Results_TypeID is the unique identifier for the type AccountService_listAccounts_Results.
const AccountService_listAccounts_Results_TypeID = 0xeb097c133ce0ccbe

func NewAccountService_listAccounts_Results(s *capnp.Segment) (AccountService_listAccounts_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(st), err
}

func NewRootAccountService_listAccounts_Results(s *capnp.Segment) (AccountService_listAccounts_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return AccountService_listAccounts_Results(st), err
}

func ReadRootAccountService_listAccounts_Results(msg *capnp.Message) (AccountService_listAccounts_Results, error) {
	root, err := msg.Root()
	return AccountService_listAccounts_Results(root.Struct()), err
}

func (s AccountService_listAccounts_Results) String() string {
	str, _ := text.Marshal(0xeb097c133ce0ccbe, capnp.Struct(s))
	return str
}

func (s AccountService_listAccounts_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccountService_listAccounts_Results) DecodeFromPtr(p capnp.Ptr) AccountService_listAccounts_Results {
	return AccountService_listAccounts_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccountService_listAccounts_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccountService_listAccounts_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccountService_listAccounts_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccountService_listAccounts_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccountService_listAccounts_Results) Accounts() (AccountInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return AccountInfo_List(p.List()), err
}

func (s AccountService_listAccounts_Results) HasAccounts() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccountService_listAccounts_Results) SetAccounts(v AccountInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewAccounts sets the accounts field to a newly
// allocated AccountInfo_List, preferring placement in s's segment.
func (s AccountService_listAccounts_Results) NewAccounts(n int32) (AccountInfo_List, error) {
	l, err := NewAccountInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return AccountInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// AccountService_listAccounts_Results_List is a list of AccountService_listAccounts_Results.
type AccountService_listAccounts_Results_List = capnp.StructList[AccountService_listAccounts_Results]

// NewAccountService_listAccounts_Results creates a new list of AccountService_listAccounts_Results.
func NewAccountService_listAccounts_Results_List(s *capnp.Segment, sz int32) (AccountService_listAccounts_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[AccountService_listAccounts_Results](l), err
}

// AccountService_listAccounts_Results_Future is a wrapper for a AccountService_listAccounts_Results promised by a client call.
type AccountService_listAccounts_Results_Future struct{ *capnp.Future }

func (f AccountService_listAccounts_Results_Future) Struct() (AccountService_listAccounts_Results, error) {
	p, err := f.Future.Ptr()
	return AccountService_listAccounts_Results(p.Struct()), err
}

const schema_b1c2d3e4f5a6b7c8 = "x\xda\xec{{x\x15\xe5\xb5\xf7Z3\xd9\xd9\x04\x81" +
	"\x9dq6\" n\xe0\x03\x0a\x91\x8b\x09\x05\x94\x07\x1a" +
	"\x12L%)h&\x17\xab\xb4*\x93\xbd\x87d\x92\x9d" +
	"\x99\xcd\xccl$\xf9\xb0Q\xbf^\x84\xde\x14E\x85J" +
	"\x0b\xf6\xa2\xd0\xf6\xab\xd0*\xea)m\xa1\xd5*J+" +
	"^\x8e`\xb5\x8f\x9cJ\xeb\x05\xabx\xa0-\xb5\xe9>" +
	"\xcfzg\xde\x99\xd9a\x13\x12\x1f\xfb\x9c\x7f\xfa\x0f\xcc" +
	"^\xf3\xce{Y\xb7\xdfZ\xeb]\xb9x\x81\xb4\xa8\xa8" +
	"|\xf8\xbc\x0b@h\\\x82\x91\xe2\xdcm\xdbW\xde\xfe" +
	"\xc6Me7\x834\x05\x01\"\x18\x05\x98\x8d#\xf6!" +
	"\xa0,\x8d\xa8\x04\xcc\x09\xcd%\xff\xb7\xe4\x94}+(" +
	"\xa3\x91F\x884b\xce\x88\x16\x1aQ5\xe2O\x80\xb9" +
	"\xb1\xab\xb6\xeex\xfb\xf1\x1f\xdd\x0a\xd28\x7f\x8a\xd1\xb1" +
	"\xfbh\xc0\xb4\x18M\xf1\xe2\x15\xed\xc5\x0f?\x90X\x07" +
	"\xca86E1\x8d\xa8\x8dm@\xc0\xd9\xd7\xc4\xbe\x8e" +
	"\x80\xbd\xcf\xee\xf8\xda\x8bsnZ\xa7LB\x81\x0f\xe8" +
	"-}\x8e\x06H\xd2\xaf\x1107\xff\x92\xbb\x8f^\xb5" +
	"\xe3\x8eu\xa0\x9c\x87\xfe*o\x9e\xcb\xb6q\xf2\xdc\x1b" +
	"\x00s\xcf\xfd\xbfg\x8e\xcf\xbbk\xcazw\x1bE\xf4" +
	"\xbeY\xeeF(\xca-y\xe2\x8f\x9b\xb1\xeb\xf6\xf5 " +
	"\x8d\x10sO\xee\xfe\xde\xc9\xd7\x9f\xdf\xb7\x13h\xff\xf2" +
	"[\xf22\x99\xedF\x8e\xa2|\x8a\x1es\xb3\xaeX|" +
	"\xe9\xfc\x97R_\x0e\x1f\xe7\x88\xfc\x18-t\\\xa6\xe3" +
	"\xbc\xbb\xf1\x8b\x9b^\xfc\x9d\xf65\x90bB\xee\xbe\xe3" +
	"\xaf\x1d\xa6)\x81\xb6\x1a/CyB<\x0a \x8f\x8b" +
	"\xdf\x0d\x98K\xcc|x\xd3\xe8\x05\xef\x7f\x0d\xa4\x11\x18" +
	",\x1c\x11hJ=^\x81r\x17\x1b\x9c\x8d\xd3\xfe\x8f" +
	"\x0e\xfdC\xf7K\x0fT}=\xbc\xee\xc181I>" +
	"\x12\xa7u\x8f^fMRb\xd1\x0d\xa1\x03\xe2\xc8\xf5" +
	"t@\xe5\x8b\xdd\xbf1\xceY\xb1\x01\x94\xe1X\x9c\xf3" +
	"\xd6\xd9\xca\x86\xc8\xc7\xe3\xfb\xe5^Zf\xf6\xa9\xf8\xa7" +
	"\x89\x93mw\xfd}\xf3{\x99Mw\x822\x85q2" +
	"\xc28u\x1e\x1dp\xb6v\x1e\x1b\xf2\xff+\x96L\xf9" +
	"\xf2\xb17\xef\x0c\xad\xb4w\xd4fZi\xc3\xab\xc2\x90" +
	"]\xcb\xfer7H11|vy\xe7\xa8\xb7\xe4=" +
	"\xa3h\xc1GG].\x1f\xa1\xa7\xdce\x7f}\xe6\xa9" +
	"\x0f>y\xd3\xbd\xb4-\x0c\xb6\x15\x19B\xc3\x9e\x1a\xf5" +
	"\x98|\x90\x86\xcd>0*G\x8b\xae\x8dM_7\xe5" +
	"{\xbb\xbe\x09J\x0c1\x98\xdbU\xb8\xc3\xa3\x05\x94\x8f" +
	"\x8e\xa6\x0f\x8f\x8c&\xa5[r\xe8\xd1W\xfe\xb9\xf9\xed" +
	"o\x9d&\x84\xbdc\x04\x94\x0f\x8caK\x8ci\x05\xcc" +
	"m\xff\xf3\xc8\x0dw\xc5Wl\x05\xe9|\x9f\xaf'\xc7" +
	"L$\xbe\xf6\x8e!\xbe^\xd7+\xed?|j\xcd\xb6" +
	"0\xe3\xc7\x8de&0c,\x0d\xd8=\xeb\x13/\x97" +
	"\xfc\xb4\xfd>\xce\xb1\xa14b\xd9\xd8\xfd\xc41u\xec" +
	"\xfd\x02`neE\xd9\xe4q\x99\x92o\x834B\xc8" +
	"S\xb1\x9a\x0b\x9f\x93\x95\x0bi7\xcb.\xfc\x11`n" +
	"\xdb\xd6y\xd7\xfd\xea\xaa\xb5\xf7\x93-\x08\x9c\xfbO]" +
	"H\xd62\xfb\xf0\x85d\x0b\xb9\xef/\xfc\xd3\xf8\xa6;" +
	"\x1e\xda\x01\xd2y\xfe~\xba\xc6/\xa7\xfd|a<\xed" +
	"g\xcb\xf1\xbf\xf6D\x7fp\xf5\x8f@\x19\x8b\x98\xbb\xeb" +
	"\x07{\x8e\x8d\xf8s\xfai\x18)D\x11`\xf6w\xc7" +
	"\xb3\xb3\xfdp<)\xd5\xf5\xd7\xbf\xbb\xf1\xd4\xdc)\x0f" +
	"\x86$9|\x02\xd3\x99+V\xfc\xad\xe577\x7fn" +
	"W\xe8M\xef\xf8\xc7\xe8\xcd+\x9b?\x99x\xa4f\xe8" +
	"\xc3\x10\xb6\xc6w\xc6\xb3\xe3\xe2\x04f\x8d\xcf\\\xf4\x02" +
	"\x8e\xdf\xfe\xe3\xdd$\xab\xa2>\xb2\x92\x0fO|Y>" +
	":\x91\x99\xcd\xc4y\xc4\x1c\xdc\xf8\x9b\x87>\xe3\\\xfe" +
	"\x08H\x93|\x0fR5y\x17\xedR\x99LL\xb9\xa9" +
	"z\xafy\xde]\xc5\xfb\xc2\":>\xb9\x8c\x06\x9c\x9a" +
	"L'\xde9\xe2\xf7\xbf\x18\xd2\xb3f\xdfij7z" +
	"\xca.y\xc2\x14&\xb1)Q\x94\x0f\xd0cNH\xce" +
	"\xff\xe3\x8e7\x1e\xde\xc7\xec\xfd\xc7\xdep\x1a\xfd\xd0\x94" +
	"\xb7\xe4\xbdl\xf4\x9e)_B\xf9\xc0\xc7\xa2\x00?\xbf" +
	"{\xfd\x13W\xdf7\xeaIe\x04\x86l\xb4\x06\xa3\"" +
	"\xc0\xec\x87>6\x14\xe5\xc7i\x98\xbc\xf7c\xb4\xd3I" +
	"\xc6}\x93\xd3{\xc7<\x05\x92,\xe6\xdcm\xbc\xfe<" +
	"\xa9\x9d6\xb5\x02\xe5\xecT\x1a\xb9j\xea\xaf\xe5\x93\xf4" +
	"\x94;\xb1\xfb\x8e\xeb\xa6\x1c\xfa\xe5~W\x92\x8c\xc7\xaf" +
	"Nm'\x1e_9t\xf8/\x8f\xad}i?(2" +
	"\x16\x05\x131\x8b}j\xea\xfb\xf2\x8bl\xa6\x83SI" +
	"\xd5w\xffw\xfa\xcd\xabkOx\xb3\xb8\xde\xe3\xa1i" +
	"u\xc4\x9d\xbd\xd3H\xc8\xbe\x06\xe4[N\x8d\x10\x15\x10" +
	"\xe5\x09e/\xcb3\xcah\xbaie4\xfa\x93\xcb\x0e" +
	"\x1dz\xff\xfeMO\x87\x04\xaf\x94m\xa0M}\xe23" +
	"\xfb\x1e\xbc}\xfa\xaf\x9f\xce\x93S\x193\x04\xa5\x8cN" +
	"?y\xdd\xffi\x1f\x1d9\xf2t\xd8R\x8e\x97\xdd\xc2" +
	"L\xa9\x8c\xe4\x94\x99\xfe\xf6cO\xbd\xaf\x1e\xe0\x9e\xde" +
	"\xb5\xa5\x8bv0[\xba\x88V\xef\xfe\x8fKF\xc5\xcf" +
	"}\xf6\xb7\xde\x1a\xec0\xeb.b\xdeu\x13\x1bp\xee" +
	"\xa4'\x9b\xdf\xbc\xfb\x95\xdf\x86\xd78u\x11s\x83%" +
	"\xd3i\x8d\x13\x97\x1c\x7fl\xe1s\xdb\x9f\x0b\xefr\xc6" +
	"\xf4\xfd\x0c\x8f\xa6\xd3.\xb74\xd7\xd5VFV\xbc\x90" +
	"\xe7\xc0\xa7of\x0e\x9c\xcdph\xca\xa6%\xb7\xfe\xbc" +
	"\xfe\xa5\x10\x07\xa4\x19\xbb\x88\x03v\xd3\x1f\xdb>7\xf7" +
	"\x91\x97A:W\xccyB\xd9G\xe2\xc5\x19\x13Q\x96" +
	"f0\xfb\x99\x11Ey/=\xe6>\xb8qiK\xdd" +
	";\x97\xbd\x12\x92\xef\xf6\x19\x0d4Qg\xd7\xbbMG" +
	"\x13\x1f\xff=(#0\xe4\x10\x98\xb9\xcb\x1bg<'" +
	"ocsm\x99\xc1,>\xf1\xdd\xdb\x0e\xc4vO\xfb" +
	"/\x90\x86\x899O|\xaf\x93\xc2.\x9c\xb5_\xae\x9d" +
	"E\xdf\xd4\xcc\xba\\^EO\xb9\xda\xe9\xe5\xdd\xe3\x96" +
	"}\xf0\x87\xd0\xee\xaf\x99EJ\xd5\xbb\xf3\xe0\x8e;\xae" +
	"\xfa\xe6\xd1\xb0\xd9\xd6\xcc\x12\x04B\xd9Y\xccl\x85!" +
	"%\xdfx\xe7\xfb\x0b\xdf\xc8\x13Oy9cMU9" +
	"q\xffT\xf1\xe2Y\xcf\xef\xaez\x03\xa4\xd1\xfe\x80-" +
	"\xe5\xcc\xf7l/'\xde=\xff\x8b\xa5U\xd8z\xf1[" +
	"\x1e\xf7\xd9\x80\x03\xe5\x7fg(\xc5\x06\xfc\xec\x99\xd7\x16" +
	"\xc8kK\xde\x0es?R\xc1\xe47\xb2\x82\x06<~" +
	"\xff\xa3\x7f~u\xe1\xd6c\xdc\x9b\xb2\x13\xd4V0\xfc" +
	"\xb9\xa6\"A\xfb\xfcV[\xd9\xb4\xbbV<q,\x1c" +
	"\x94\xdc8\x9b9\x8c\xaf\xce\xa69\x16\x08\xff9tn" +
	"s\xfa]\xcf$\xa24`\xe7\xec\x06\x9ab\xcfl\xc6" +
	"\xd2\xa3\x9fz\xf0\xd0\xea\xec\xd6wO\xf3\x01\xd7\xcc\xd9" +
	"'\xabs\x88\xa5\xd7\xce\xb9\\\xfe\x02=\xe5vT\xfc" +
	"\xac}\xd6\x97\xdf{/\xbc^\xe7\x1c\xb6\xde\x8dsh" +
	"\xbd\xad\x0f>q\xcf\x0f\xff\xb6\xe5D! \xdf6\xa7" +
	"\x0c\xe5\x9dl\xc6\x1f\xce!\x1e~{\x9fZ}\xcbA" +
	"\xe9d\x98\x03\xd2\\\x16\xa9\x8c\x9bK\xb3\xfd\xbcz\xdb" +
	"\xef.\xba\xf0\xde\xbf\xe4\x89a\xe1\\&\x86esi" +
	"\x8a\xcdSGn\xbetl\xd1\x07a\xc5\x9a\xcb\x14\xeb" +
	"\x9e/%f\xfe#yAoa\xdf\xbfq\xee\xb94" +
	"\xc9\x96\xb9\xe47~\xd7s\xe2\x1b/\xbd\xfc\xe3\xde\xb0" +
	"\xdfX7\x8f\xf9\x8d\x8d\xf3h\x95\xd7\x85#\xaf}\xfa" +
	"\xba\xa3\xbd\xe4\x840pBl?\xf2\xc9y\x7f\x97\xf1" +
	"\x12z\xea\x9dw\x03\x98\xb9dZ\xcd\xa6\xb4\xebW\x15" +
	"g5\xabkfR\xcd\x18\x99\xf9\x8b\x19M!J\xa3" +
	"f\xad\xd6\x93\xda\xccV\xcd\xa9\xb7\xcc\x95zZ\x9bT" +
	"\xafZj\xa7\x0dJ\x91X\x04P\x84\x00\xd2\xf0\x06\x00" +
	"e\x98\x88\xca\xf9\x02\xe6\xd4d\xd2\xcc\x1aN-`\x0a" +
	"\x87\x81\x80\xc3\xc8\x7fX\xe6\x1a\x9a\xbc\x88f\xaf\xa7\x1f" +
	"|\xde\x8ce\xb6h\x8c2\xa9A\xb3\xb3\xd1\xb4c+" +
	"\xa5\xfe\xc4j5\x80\xf2Y\x11\x956\x01\x11\xe3\xc4U" +
	"I#\xda\x0a\x11\x95\xb4\x80\x92\x80q2\x0aI\xa7\x1d" +
	"\xb4\x89\xa88\x02J\xa2\x10G\x11@Z5\x1f@I" +
	"\x8b\xa8\xac\x11\xb0\xc7\xce&\x93\x9am#\x82\x80\x08\xd8" +
	"\xd3\xa9\xd9\xb6\xda\xaa\xe5o\xb1\xd6X\x09hbi\x10" +
	"\xe2\x00b)`\xa5\xa3w\xeaF+\x96\x06!\x99\xfb" +
	"\x82\xd8g\xa44{f\xc4\xe7\x1c\xfd\xe4\xa7\xf3x\xe1" +
	"\xfd\x0cN\x18b\xddD\x00e\x88\x88J\\\xc0\xa8\xbd" +
	":\x89R\x10\xd6\x02\xa2\x04>C\xf9\x12Uys\xce" +
	"\xccfR\xaa\xa3yDW6h+\x17\xf8\x0b<D" +
	"\x9c\xf9\x89\x88\xca/\x02\x16\xeei\x01P~*\xa2\xf2" +
	"d\x88\x85\x8f\xd7\x01(\xbf\x12Qy6\xc4\xc2\x03\xcb" +
	"\x01\x94gDT\x0e\x09(\x15\x89q,\x02\x90^$" +
	"\x09<+\xa2\xf2\x8a\x80R\xa4(\x8e\x11\x00\xe9p7" +
	"\x80rHD\xe5u\x01\xa5\xe2H\x1c\x8b\x01\xa4#\x1b" +
	"\x00\x94\xd7ET\xde;\x83bx\xb4&\x88ve4" +
	"\x8c\x05\xf1\x16 \xc6\xb8T\x9a\xad4\x00\xf8\xdf$M" +
	"c\xa5\xdeZg\x83h\x1a\x9c\xd8\xb3Z\xb3l=\xf8" +
	"\xed\xa9uc\x16*[\x16[Z\xca\xc6\xd2\xc0\xd8\x03" +
	"\xd1eSZU\x06\xf5Oi]4\x08i\x94\x1f\xdb" +
	"\xe7\x8d\xba^-\xce:my\xe6Q\x95u\xda\xb8\x10" +
	"\x92fg&\xad9\xdaR\xb3U7\x98\x98\xd3\x0e\xda" +
	"\xcax_\x0a\x07\xab\x03>r)\xe4\xb1\x91K\xe1p" +
	"K\x88\x8d\\\x0aG\xda\x01\x94\xd7DT\x8e\x91\x14\xd0" +
	"\x95\xc2\x9b$\xd87DTN\x90\x14DW\x0a\xc7\x89" +
	"\xf8\x9e\x88\xca?H\x0aE\xae\x14NU\x00('D" +
	"l@\x01\xa5h$N~@\xea%y\xfdC\xc4\xc6" +
	"!8\x00\xebP\xd9\xeb&\x13\xa2\x1dZ\xc0dK[" +
	"iiv[\x13\xc4\xcc0Y[\x93\xd1-\xcd\xae\x05" +
	"4\xb0\x04\x04,\x81\x82\xc2Oh\x9d\xaa\x9e\xf6\xbf2" +
	"\xadV\xd5\xd0\xbbU\xa8tt\xd3\xa8\x0dt$\xa9\xa6" +
	"\xd3-j\xb2\xa3\xc8c\x7f\x83\x99u4k\xa6ix" +
	"J_\xb3Zs5?\xaav\xda\xca\x10\x9f\xe7\xd3\x88" +
	"\x17SET>\x1e\xf0\xbc\xbc\x0c@\x99.\xa2rI" +
	"a\x85\x8cu\xe8F\x0acA\x1a\xe2\xe9!7\xf3\xa2" +
	"\x82f\xde\xaa9W\xb9\xfa7\xa9\xd2\xf5\x8e\xbe\xd1\x0a" +
	"}\x8d6F_\xd4#*\xa5b\x04\xc0\xcf\x1b\x90\x87" +
	"X\xd2\xaa[@\x90\xf4(\x06\xf95r|\x97\xae\xb5" +
	"@\x90\x9a\xa3(\xf8\xe1\x14r\xd0\x91j\xe9]U\x14" +
	"E?\xa1D\x8e\xd9\xd2\x9cv\x10\xa4\x19\xd1\x9c\xa5\xb5" +
	"\xea\xb6\xa3Y\xe8\xed\x07\x16a\x8e;\x10H0\xd2\"" +
	"\x12k\xa7\xb9:\x8f\x92\xd6m\x87>\x81X\xd6p\xec" +
	"EX\x8fg\xf3|\xc9\xbe62\xa9\xa1\x92\x99\xc5Y" +
	"\x9c\x9f\x1f\xa9y\xce\x8f\x0b_\xf4\x84\xdf\xd4\xa6\x1b\x1d" +
	"\xba\xd1\xbaT[\xad\xa5\xaf\\\xadY1KO1~" +
	"\x9e\xcf\xec\xa7j9\xfbra\x1d\x00\x0a\xd2\xa5\x13\x01" +
	"P\x94\xca\xe7\x03`\x914\xad\x0c\x00#\xd2\x84\x0a\x80" +
	"\x9ca\xd2\xc7\x96\x0ebJ\xcb\xa5t[mIk)" +
	"\x00\x88\xa6\xcd\x1b*;\xb5\x94\x9e\xed\x8c\xb5\xe9\xadm" +
	"\x895\xf4\xaf/N1\xcf\x03d\xb8\xe7\xd0\x8c\x84\xa3" +
	"\xabi\x9b\xf6\x11R@\xc2\x9fI\"*\x17\x0b(q" +
	"\x0d\x9cQ\x1dhe\xa5\xcaf\xf0\x9dX\x8bjk\xcd" +
	"V:\xec\xc4\xfaaq&\x84\xa3\x81\xcf\xe9\x97\xbb~" +
	"@: h\xe1R'\x99s\xd4\x87\\\xd2\xec\xec4" +
	"\x8d\x99IA\xf5\xc0\xbcEkb\xe8\x08\xc0\xc4\xe0\xaf" +
	"\xbf\xc9\x02P\xee\x11Q\xf9N\xe8\xf8\xdb\x88\xb8UD" +
	"\xe5\x07\xe4\xf4\x04\xd7\xe9m'\x94y@D\xe5'\xe4" +
	"\xf4D\xd7\xe9\xed$O\xf8\xa0\x88\xcaO\xc9\xe9\x15\xb9" +
	"N\xef\xd1\xea\x00\xcd\xa4H\xc4uz{\x88\xf8\x88\x88" +
	"\xca\xaf\x04\xe2\x99\xae\x19Nu\x16\x12z:\xd5l\xfb" +
	"\x0e\xc8\xd2Ve5\xdbi\x84\x84f\xa4\x96\x05\xf4\x16" +
	"3\xd5\xd5\xa0\xa9)\x10C\x83\xdbm\xd3\xa8W-\x1b" +
	"\xa2Z@\xedqLGM\x07\x9f\xf6\xd0\xa7K\xb5\xc0" +
	"\xc7\xf1P*r\xd6P\xaa\x99\x9ck`\x11!\x9e\xd1" +
	"Q\xee\x14Q\xd9\x1a\xf8\xac-\xd5!>r\x9c\xd8V" +
	"\x17\xe2#\xc7\x89\xedu!>r\xb4\xde\xd9\x1d\xe2#" +
	"G\xebG\x97\x07,;\xab\xf3_\xa9\xaf\xd6\x96\x98Y" +
	"\x8b@\xb84\x88.=\x80\xb4\xb5\xd5\x9aq\x99\xdau" +
	"\x96\xb7\x95\x8d\xa6ahN\x81!\xda\x1a\xc7R\x9bm" +
	"\x15\xc4V\x0dK\x83\x14\xfa\xc3DX\xa4\xa5b\xa7\xed" +
	"\xbb\x0d\xc1\x13C\xbd\x99\xd6\x93]a\xf7[\xc4\xdc/" +
	"\x8f\xe9\x91g_\x92T\x0d\x82\x14\x89\xf6$i\xbbI" +
	"\xc7\xf3u\x9e\xce#\xd7\xf9J\x16+\x9a4\xd1$_" +
	"x\xef\x8c\x09!2\x97\xdeq\x92\xde1\x11\x95\xbf\x85" +
	"\x14\xfe\xe4\xfc\x10Ls\x85?U\x16\x82i\xae\xf0\xbd" +
	"\x0d!\x98FW\xe1\xe5\x08N\x04h@\x11\x1b\x87a" +
	"\x10m\xc9%\xd8\x0d\xd08\x84\xe8q\x06\xf5\xc5\x0c\xea" +
	"e\x09\xcb\x00\x1a\x87\x11\xfd|\xa2\x0f\x89\xc6q\x08\x80" +
	"<\x12\xeb\x00\x1a\xe3D\x1f\x8f\x02\x8az\xc6\xf7D\x8c" +
	"\xa9\x96\xef\x99*\x098\x82\xe8*\x96\xd4\x9d\xaep<" +
	"\xe6\xe8\x86f\x00:\x9c\x16Um\x03\x87\x80\x80C\xc8" +
	"\xc9\xd8W2h\x87\xcan\xd5\xc9\x9b\xc5L\x9b\xfe," +
	"\x8e\xde\xa9u\x9b\x86\x96\x17\xe9\xf5q\xfe\x8d\x8e\xa5\xa9" +
	"\x9d\x8b\xdb\xb2F\x07\x03}pq\xd4\xcf\x16\x1a\x82\xcc" +
	"\x80\xb3__\x1eJ\x0c\xb8\xf1\xac\xa2\x81\x19\x11\x95\xb5" +
	"!\xe3\xe9\"\xf6;\"*7\x9d!VM\xd2\xba\xb5" +
	"F\x0aDm\x8d\x7f8Ro\xa7\xa9+\x03\xe8\xdbK" +
	",\xa5:\xea\x19\xcf\x10\x0eZ>\xa5\x1b)\xf7\x0cl" +
	"[\xd3*\x98_\x9eP\xcd\xb0kt\x03\xc3\xae\x91\x16" +
	"@BM\xa5\xb4T\x8f\x8b\xcb)\x1evi\x80)/" +
	"\x18n\xce@\x82P<\xe5[\x8b\x07T\xd5\xa6\xe9\xd8" +
	"\x8e\xa5ff\xaaY\xa7\xcd\x0f\x92B Q\x11\x80D" +
	"\xc2\xc9\x0b\xe3\xf8T\xc5\xfd\x00|\xd8\xb1y\x18\x94\x9f" +
	"\x19\x9e\x8eA~\xa9\x8d#\xfc\xa0\x13P\xbe\x0e(\x17" +
	"\xf3\x85\xe4*\xac\x06h\\@\xba\xbc\x04}\xf1\xcb5" +
	"\x8c\xbc\x88\xc8K1\xd0\x00\xb9\x16\x1b\x00\x1a\x97\x10\xbd" +
	"\x09\x03%\x90\x15\xac\x00h\\J\xf4\xab1p\xa2r" +
	"3\xb6\x0046\x11}\x05\x06~T\xbe\x96\xcd\xf3Y" +
	"\xa2\xb7\x85MQc\xa6\x98\"z&l\x8a\x9d\xb8\x1e" +
	"\xa01C\xf4\xb5aS\xecB\x0b\xa0q\x0d\xd1?O" +
	"\xf4\x12\x8cc\x09\x80|3\xee\x00h\xfc<\xd1o#" +
	"\xfa\xd0!q\x1c\x0a \x7f\x95\xed\xe7+D\xbf\x87\xe8" +
	"\xe7\x94\xc4\xf1\x1c\x00y#\xee\x02h\xbc\x87\xe8\xdf\x19" +
	"`\\\x7f\x96\xb0<\xa5\xdb\x99\xb4\xdau\x05D\xd5\xce" +
	"\xe0\xbb\xa4\xa5\x91\xbaU\x85l\xfe\xcc\x01<\x7f\x81D" +
	"o\xea\xcah!\x13\xb7TG[\xaaw\xea\x90p\x9a" +
	"t\xcd\xf2\xe9m\xaa]C\xb8\x80\x0c*k\x0c5F" +
	"\x01\x1a?G\xaeEO\xa7u\xa3\xd5\xcb\x1b\xf9Gv" +
	"\xb6\xc5NZz\x86-\xb4\xd8\xd2\xd4\x04\xed\xd1\xe9{" +
	"\xda>AySW\x06\x19$\\\xc0\xacpY5\xd3" +
	"\xcc\x9a\xcd\xcc\x0ak\xd63+\xac\xd9\xc0\"HF\x8c" +
	"H5\xed\x00X\xccb\xcd\x9e\xac\xd1a\x987\x18~" +
	"\xc2\x89\xee\x16\x1c]49\xb1^\xc5\xae*\xfb\x1a3" +
	"{\xb9\xc9\xe2\xa7\x94\xb6\xa61\xdb\x82\xde8\x13\x8d\\" +
	"\xab\xd6\xa9\x1bz\x9f\x8f]bU\x06b\x14$\xe6\xd4" +
	"\x1b\xecj-e\x99 &;\xce\x12\xb8\xf10?T" +
	"\x15`f\xff\x91U\x05\x08\xd3\x9e\x14Qy!\x14g" +
	"\x1c\\\x1e\xae\x0a\xa0W\x15h\x08W\x05\xbc|\xf4H" +
	"K\x90\xce~TU\x81\xd3\x0b\x00\x05\xaa\x04\x053\xd3" +
	"$\x8b\xdf\x1d\x1d\xa2j\xda\xc6R~o\xc0\xa3\x8f\xc2" +
	"\xc9\xa7E\xff5\xb8!\xa5\xeb\x8f\xc4\xfc\xccf~\xe0" +
	"\xf7*-76/\x0d\xcaz}&\x17\xc3\x93\xbb\xde" +
	"m\xa6\xa5\xb5k\xc9\xa8\xa3\xa5\xdc\x84\xc2e\xfc\xb4\xe5" +
	"\xf9)-\xf1\xbd\xbc:\x94\xd2\xda\x8e\xead\xed\xc5&" +
	"\xa55\x18\x05\x01\xa3\x05\x8c~\x10iE\x10\xf5\x0f " +
	"\xdb\xcb\x03\x03\x9e\x08\x0f\xa8~\xc2\x0b\x09\x84?!\xf7" +
	"\xfe\xef\xfa\xc9GY?\xe1\xb10\xf3\xa8\x0dZ\xc6\x14" +
	"-\x87\xdc\xdeT\x1fDK\x18\x9a\x05\x01$GQ\x09" +
	"\xe7\xe7\x05\x90^\x18+\x8fdhYJ\xf4\x0b\x08t" +
	"\xdd@V\x1e\xcd\xc0\xe9|\"O\xc2\x80\xe3\xf2\x04l" +
	"\x07h\x1cO\xf4\xe9\x0cD\x05\x17D\xa71\xf0\x9bJ" +
	"\xf4\x8f3\x10\x15]\x10-\xc7\xe5\x00\x8d\x17\x13}\x01" +
	"c\xbd\xe0\x82\xe8\xa5\x8c~\x09\xd1/c Z\xec\x82" +
	"h\x15\xde\x92\x07\xf6%Q\x17Dk\x19\xe8\xfa\xa0^" +
	"\x88\x97}2\xf1D\xa7\x99\xd2\x02\xd6\xeaF&\xeb4" +
	"\x99\x1d\x10\xd5\x0c\xdb\x0f\xfd\xcc\xac\xc3\xc8\x10\xeb\x08\x93" +
	"\x1d\xafB\x01\x09V\xa3\xf0\xe9y\xa6\xc9\x89\xa9\xac\xc5" +
	"bb\x10C)iRM\xb6i\x0d\x9a\x8a)f\x10" +
	"6\xf8\xc3\xd9\x9bO[::\x9a\xf7*\xf4\xce3\xb4" +
	"H\x7f\x86f;\xaa\xe5\xb8U\xca\xfa\x043Pe\x98" +
	"od5d;\x97\x89\xa8\xd4\x87\xf2\x97e\x04\x00K" +
	"ET\xae\x0e\xe5/\xcddz\xf5\"*\x9f\x15H\x8b" +
	"S\xba\xa5%\x1d\x886[z~=\xfdl>\xba\xdf" +
	"`\xb5A\xb3c}\x0bF\xd5\x81[\xed\xb1\xdd3\xa1" +
	"\x14\\\x0c\xf7)\x1a!\xf7\xab\x09\xe6\xb5\x83\xaa\x1b\xbf" +
	"gB~'/\xadj\xe7U7~\xbd\x82\xfc\xb2F" +
	"\xba\xb6\x85W\xdd\xf8\x95-\xf2\x1bB\xa9\xb6\x85W\xdd" +
	"x'\x0b\xf2\xdbaiN\xb7Wu\xf3\xc0\x02b\x04" +
	"\x17\xac\xc0\x961-\xa7\xd9\x86\xa8\xda\xaa\xf9\xbf\x17\xb7" +
	"A4kt,\xc2\x1c/mB\xa5\x9b'\xe4\x17\xdc" +
	"\x84\xbe.\xd8\xcfi\xcfg\x87\xe3]\x1e\xc8\x1bx\xa4" +
	"\x9d\xb4\x91\xedt8~E\x8a\xbc\x1bF\xda\xb2\x01\x04" +
	"i\x13\x1d\x8ew\x0e o\x9c\x90\xbe\xba\x19\x04i\x1d" +
	"\x1d\x8e\xf7\x1b \xeff\x91n$\x86e\xa3X\xe4_" +
	"<#\xbf\xa0\x95t\x0b\x04I\x8db\xc4o\xdeA~" +
	"\xc5,5/\x07AZ\x16\xe5F\xd8\x08\x95\xae\x18\x17" +
	"\xf9\x05\xf9,r}\xc5\x80\xaad\x91\x83\x8b\xc8\x06s" +
	"\x98\x82\x98\xf7u\xc6K\xf1!\xc1\xe7\xe3eY\x0a\x01" +
	"\\\x16\xf6)\xe3y\xf1\xd1b/\x02P\xd3\xb6[\xc3" +
	"\x1a&\x16\x0d\xcb\xe5\\\x9b\xa0\xacp\x91\x88\xcaR\x01" +
	"\x87\xe3?s\xaeQ\xd4\x92\xf3_\"\xa2\xd2$\xe0p" +
	"\xa17\xe7Z\x85\xb2\x01@i\x12QY!`\xcc\xa0" +
	"\\\xb6\xf8#\xbf\x87X%\x9e)Mr\x8f\xedn\x9f" +
	"\xd4\x80w\x80!os\x91\x14b}-\xa9\x01\xbf\x88" +
	"E\xde4$-\xac\x03A\x9aCj\xc0/M\x91_" +
	"\xe8J\xd3\xe8\xdd\x84h\x8e\xa7` \xa6=\xf62(" +
	"\x01\x00\xf7W\x83\x99\xd6l\xf6\x8b\xa9\xeb\x80\xca\xf6\xdc" +
	"\xc8\xfd\xf3\x09\xa1\xf3\xb1\x0c \xc1\x169s\xa6\xef{" +
	"*\xbd=\x9c\xea{\x9ejUK8\xd5\xf7*-]" +
	"D\\#\xa2\xf2y\x01s\xba]c\xa8-i\xca\xa6" +
	"\xfd\xf4\xa2\xd34\x9c\xb6t\xd7R\x88\xe9\x9d\xba\x83\x11" +
	"\x100\x02\x98\xcb\xdaZ\x8a\x04\x04Q\xdd\xb1\x03\xaa\xa3" +
	"\xa7\xf5n\xd5\x81(\xf9\xb6s@\xc0s\xfa\x09\x1c=" +
	"S\xcf\x1a\x1d~pu\x86;\x0b\xff`\xe5\x15\xa1\x08" +
	"\xcf\xabc\xe6\x05\x02\xac2\x81\xa5A\xabU\x9f\xf8R" +
	"\xe8\x1b_\x8ai\xc7+U\x0f\xcb\xe5\x10\x83\xdbgi" +
	"\xda|\x10H\xcf1\xd4\x8e$Iu T2/\x96" +
	"\xca\xb1\xb8\xd4a\xb5\xf2\xb3\x05\x92\xbc\xe6\x16D\x92\xf8" +
	"a\xe2A~\xdf\x1c\x02\xaa\xf6\x0f\x09T\x05\xc3\xad\xc1" +
	" U\xe4l\xf7?\x85j a\xd0\xea;\xf1\xe0\x12" +
	"9\x1f\x12C\x1aS\x1d\\2\x14\xbac8kh:" +
	"\xd8\xb8\xc1\xafZ\x17\xdeCp\xd1\xd1\x10hm\x0f\x01" +
	"z\xf8f\xc3\xd6lbC\xa1\xac\xef\x8c\xacp/\xa5" +
	"\xf2\xef\xb9\x07\xd1\x83\xf0!.r}\x03\x0d\xa9^C" +
	"!\xd5+\x0b\xe0\xc0W=\xa5%\xa4z\x05\xce\x1bK" +
	"\x9a)\xed\xb4 \x9d\x82\xa8\x01_\x00\xe5\x19X\xa1," +
	"\xf4\xf4\xea\x9b\xdf\xe8\x19T\xdf\x06u\x8b\xe7E\x8d>" +
	"7\xc53q3\x9aw\xcd\xc9[\x05\x91\xf7\x89I\xab" +
	"\x96\xf3\x80\x8b7~\xe1\xb3\xe0v\x0b\x87\xae9y\xeb" +
	"\x1a\xf2\xe6E\xa9\xb6\x9d\x07\\\xbce\x09w\x82\xdb " +
	"%\xcd\xb9\x0f\x04\xa9<\x9a\xe3\xda\x0a\xa2n,b\xd5" +
	"{&TH0\xb1.\xea\xeb\x09\x02B\x15z\x95\x07" +
	"3\xca\xe8\xfd\xe0X\xd8\x91\xf3\xcb\xb73\x14\x98j\x8d" +
	"\x95\xc8\xae\x0a\xfe5\xf5\x17/\x9f=\xd8\x10\xae\xbfx" +
	"\xf9\xec\xe1\xe5\xff[\xf5\x97\x82\xa5\x96B5\x99\xfe\xeb" +
	"/\xbcsH\xe8\xdb9\xe4Fj\xee-\x0e\xefnC" +
	"\xde\xd4.I\xa4]%\xd1\x1co/\x02qMWa" +
	"q\xd6\x87\x8dh\xa6w\xebsZX\xa2F\x07\x00W" +
	"\xbc\x9e\x98W\xc5\xf8w\x11\xe3#)b\x0c\xa6\x09\xca" +
	"\xf7\x84\x1f!J\x0e\xa8\x83\xcd\xbb}\x0c{\xe0\xba\x10" +
	"*\x15lf\x1aD8\x94\xa7_^}m0\x088" +
	"\x88\xdb\xfeB\xed\x04\xfc(S\x83\xe9)\xda\xc7\x11\x80" +
	"\xf5\"bi\xd0\x1c\x0bH\xc4A\xdc\x87\xb3\xcc!\x88" +
	",\xe2\xfe\xa27V\x07\x91:\x97\xdb\xcdD[+\xa2" +
	"rk\xc8d\xbe\xb0\x1e@\xb9UD\xe5\xce\x90\xc9\xdc" +
	"n\x01(\xb7\x89\xa8\xdc\x1b\xaaSo\xa2\x91\xf7\x8a\xa8" +
	"<0\x00\xb1\xe7]]\xd0.C\xa2\xbb\xc1\xb4:\xec" +
	"\x8c\x9a\x84\x84Fo\x0a\x7fs\x85\xda\xa9\x9d.\xee\x01" +
	"\xb7\x08\xf0\"\xcd`\xe2\x9c\x01T\xac\xfbo\x13\xf4\xe3" +
	"\x9a=\xf3\x83.\x01?\xae\xd9[\x11\x82)\x9eQ\xe5" +
	"\xc1\x14\xbf\xbb>\xd0\x10j\x1e\xe4\xcd\x1a/\x12\xf1\x05" +
	"\x11\x95\xd7\xc89\x15\xbb\xce\xe9\xd5[\x00\x94WDT" +
	"\xde(\x9c\xe1\xf4_\x9e\xd3\x8cT\xc6\xd4\x0d'lW" +
	"Y[\xb3\xaaZ\xf3.\xa5\x0b\x06\x9dn\xbbH\x83\x86" +
	"\xee\x9a)8-\xf6\x12\xfa\x14\xa7B\xb8\xc3\xff\x04\x05" +
	"\xf9\x1f:HR\x19\xeb\x1e\x88Q\xbc\xebWm\x06e" +
	"\x04\x1fB\xe2\x05\x9b\x93\x98\x97\xf0*\x1b\xb1\x02\xbdI" +
	"-\x85\x12\xcdvv\xa7\x8a\xca\x02a\x90\xde~`\xa8" +
	"Z\xe0\xfa9\xef\x9e\x84i*J\xc1\x9f\x85\x0c\xa8M" +
	")?3\xf8W8\xff~C@\xaf\x97\x87\x87\x80\xfd" +
	"\xde\xe9\xd03\xa6\xceZ\xc8\xb0\x82B\x06\xf2:\xc6\xae" +
	"\xa0;A\x12\xc7\xbb\xb6t#\xb9\xb2\x9bDT\xber" +
	"\x06\xcd`vr\xe5j\x0d\x12\x96\xa5\x87\xb2\x0d^\xa3" +
	"F\xdeF\xe7\xbd\x8f\x05\x7f\x04\xe7\x85zv\x87\x9e\xa9" +
	"\xd6\xd3i\xd4\x8d\xd6\xc5mZ\xb2\x83^xU\x92\x01" +
	"\xb0e\xc0%\x8e\xf9\xfd\x978*\xddI\xb14\xf8\x13" +
	"\xa5>u\xb1p\xdd\x88\xad]Y\xafY\xba\x99:\xb3" +
	"\xda\xfbk\xd7\x85\xb4\xbep1\xc7\xd2l\xcd\xb1\xab\xc2" +
	"\x1e\xe6\x7f\x02\x00\x00\xff\xff\xc7<s@"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b1c2d3e4f5a6b7c8,
		Nodes: []uint64{
			0x812a80e89166a990,
			0x8873f9097b095502,
			0x88afc5ebaaa0711b,
			0x891fa8b6066a4ed5,
			0x898035d58eaa00d0,
			0x8993aa56e597383a,
			0x8a269637f1cc83d2,
			0x8a9179019ae6c648,
			0x8b64d73a39434e2f,
			0x8e65dbd5998695ef,
			0x8ef23c1999b62e1f,
			0x8f41a8d77ae30ae5,
			0x92070f51247244e5,
			0x92600b6ece7a8651,
			0x949970f09afa9668,
			0x94e9ec8b264832ae,
			0x97f64db20802dd92,
			0x9c8046fbc9ccf744,
			0x9eb2a626892c0f7c,
			0x9feb9afedcb9d848,
			0xa06014969215eea9,
			0xa178f9d9ca11fd5e,
			0xa26abc09da3e2fb7,
			0xa309701d252a3266,
			0xa77c56c45e37a0a1,
			0xaab5935420e73dab,
			0xaf58ac077ff7f19d,
			0xb02636f995ef5f5f,
			0xb27e81ce62f8604e,
			0xb60a45b81f469adc,
			0xb7b3a92001d42bcc,
			0xb847745bb5ce9501,
			0xc20696166fc14280,
			0xc2787f08c0de0eb1,
			0xc2b6e8aae63a6302,
			0xc80017a258c68a97,
			0xc91ac16c25a26e24,
			0xcac3d8265e93b7f4,
			0xcad77cecc30d0a4f,
			0xcaf44958e96cf3b7,
			0xcb6cee0eecbdac96,
			0xcb99a7f2d8d84d46,
			0xcbc72c91b0c25b3e,
			0xcbe105196a238925,
			0xcd61f2c9baeb2c70,
			0xcfd012141738bb7a,
			0xcfdc97e955c82412,
			0xd2a9d23dbaf138f4,
			0xd460053f494a559d,
			0xd750bf88489926d8,
			0xdab8367e68e65473,
			0xdc44ed4a624c7dfb,
			0xde341fe554ef796d,
			0xe229b70fcd90a51f,
			0xe3fb4d1d7a312c49,
			0xe59e5693aad100b1,
			0xe83dabed9b090802,
			0xe841b7d32f4306f9,
			0xea306701414cc0d3,
			0xeb097c133ce0ccbe,
			0xeca03dddeeb9a7c5,
			0xecc66096292a689f,
			0xef6c55360ad6023c,
			0xefa07576d8b04be5,
			0xf0f08b2f6abe32aa,
			0xf49df8ad98c6b0a0,
			0xf511d1824261c2a3,
			0xf69c1e2bdba142bf,
			0xfb041b399a15289a,
			0xfd1c63fc2e1f8798,
			0xfdb3dad79bf47fdb,
			0xfde55e57e0e102e4,
		},
		Compressed: true,
	})
}
